### ISSUE TITLE
Feature request: allow streaming through vlc, or other video players

### ISSUE THREAD

**Issue by lostb053** [fakeyatogod/AnimeScrap#1]
Well, to be honest, I'm really satisfied with this app.
I like how simple it is to use, no ads, simple and good user interface.
Player (i guess i should call it in-built) is simple, but you can't seek like in vlc or most video players available nowadays by simply swiping or double tap.
If it's just streaming, redirecting streaming link to vlc app should be easy is what I'd like to believe, but I'm no developer, so I'll leave it up to you.
A small suggestion: make a small settings page with these two options for starters, colour for the app ui and enable/select external player.

**Comment by lostb053** [comment]
Not sure if this is what you meant in [here](https://github.com/fakeyatogod/AnimeScrap#%EF%B8%8F-donations), but i surely am treating myself with ice cream while enjoying your app

**Comment by fakeyatogod** [comment]
> Well, to be honest, I'm really satisfied with this app. I like how simple it is to use, no ads, simple and good user interface. Player (i guess i should call it in-built) is simple, but you can't seek like in vlc or most video players available nowadays by simply swiping or double tap. If it's just streaming, redirecting streaming link to vlc app should be easy is what I'd like to believe, but I'm no developer, so I'll leave it up to you. A small suggestion: make a small settings page with these two options for starters, colour for the app ui and enable/select external player.

Glad you liked the app. And thanks for the suggestions, will do something about the seeking perhaps. As for external player, will try 🤞. Dunno about the theme color thing. Will be a overkill I guess.

**Comment by fakeyatogod** [comment]
Keeping it open till then

**Comment by fakeyatogod** [comment]
> Not sure if this is what you meant in [here](https://github.com/fakeyatogod/AnimeScrap#%EF%B8%8F-donations), but i surely am treating myself with ice cream while enjoying your app

Cool, try not to get brain freeze hehe

**Comment by lostb053** [comment]
Thnx, no worries if applying colour change doesn't seem to work out. A small suggestion to make users more attracted to app. Dark theme is lit already.

**Comment by fakeyatogod** [comment]
Thanks.. I use dark mode all the time anyways hehe

**Comment by fakeyatogod** [comment]
Added external player support added in [`1.6`](https://github.com/fakeyatogod/AnimeScrap/tree/1.6)

**Comment by fakeyatogod** [comment]
Also added double tap to seek on default player. Peace

**Comment by lostb053** [comment]
Nice

**Comment by lostb053** [comment]
What does dynamic colour mean?
Is it something like system theme colour, as in Google's phone and message app. They change with wallpaper

**Comment by fakeyatogod** [comment]
> What does dynamic colour mean? Is it something like system theme colour, as in Google's phone and message app. They change with wallpaper

Yeah, exactly

**Comment by lostb053** [comment]
Nice, perfect. Actually works for my reason i suggested to add custom theme colours. Cuz i like blue
