### ISSUE TITLE
Can we get a feature to turn off subtitles for zoro 😅 ?

### ISSUE THREAD

**Issue by anidevrev** [fakeyatogod/AnimeScrap#11]
Can we get a feature to turn off subtitles for zoro 😅 ?

**Comment by fakeyatogod** [comment]
Yeah I was thinking too. Was looking for a place for the button in the player. Dunno where to put it for the player to not look bad.

**Comment by anidevrev** [comment]
Thanks for the reply !! Hope you will figure it out and we will get the feature in a future update 🥳

**Comment by fakeyatogod** [comment]
Added in 2.2.0
