### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by killerlearner** [fakeyatogod/AnimeScrap#16]
I just installed app and it seems it having issue with claming data from Zoro whenever I use Zoro as server it says no url found whenever I play any anime while works perfect in other server. 
And can you please add subtitle on off feature as cc where when click shows and when not it's not.

**Comment by killerlearner** [comment]
And also can you add dub feature like if dub available then show of viewer wanna watch in it or not and if not available then not show. 
+ Watch history will be great

**Comment by fakeyatogod** [comment]
Fixed Zoro and added sub toggle in 2.2.0. Added AllAnime Dub for now for the normies for now. Will add option directly in the episode selector later if I redesign it later.
