### ISSUE TITLE
zoro dub

### ISSUE THREAD

**Issue by Harshdeepsinghh** [fakeyatogod/AnimeScrap#18]
pls add a feature to change zoro audio track button inside the player.
and pls don't zoom subtitles in full screen mode and also I prefer subtitles with black background color.
thank you.

**Comment by fakeyatogod** [comment]
I have noticed the subs issue in full-screen too in jk 0. Will have to do something about it. I like subs having transparent bg. I think the outline could be a bit bigger to make it look like hard coded subs.

**Comment by Harshdeepsinghh** [comment]
also if you could add a  setting to select preferred subtitles background 😅
