### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by killerlearner** [fakeyatogod/AnimeScrap#19]
Just noticed a bug when we keep at allanime (dub)  for quite some time like 2 days search function stopped working so need to change at other server like Zoro and then again at allanime to work. Don't know about other server but i noticed it at allanime dub server.

**Comment by fakeyatogod** [comment]
Allanime's server is kinda mad like that. I will see what I can do.

**Comment by fakeyatogod** [comment]
Fiixed with 85df42c6a945222985bb3ef85f89ef13fab03449
