### ISSUE TITLE
check for updates

### ISSUE THREAD

**Issue by Harshdeepsinghh** [fakeyatogod/AnimeScrap#22]
plss add a check for updates button in settings

**Comment by fakeyatogod** [comment]
Added updater in ee6782e401188f4fd2ceac6b3f08f9e67db70b61  2.2.3. Will check for updates on the app start.

**Comment by Harshdeepsinghh** [comment]
thank you 😊

**Comment by fakeyatogod** [comment]
Added in bd3b6806d6a98ac39626a630c09be1fb9f1ce065
