### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [fakeyatogod/AnimeScrap#39]
Please add the themed icon.

![Screenshot_2023-02-24-00-05-34-435_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221024758-c2c2ae51-4374-421e-a70c-c03678ad0001.jpg)

**Comment by RuDru-OP** [comment]
Themed Icon would be added by your theme developer not the app developer

**Comment by xmha97** [comment]
It's a feature of Android 13.
It is not an icon pack or theme.

**Comment by fakeyatogod** [comment]
Added
