### ISSUE TITLE
Yugen URL change makes the app unable to connect

### ISSUE THREAD

**Issue by KinimodD** [fakeyatogod/AnimeScrap#40]
Yugen changed it's URL from yugen.to to yugenanime.ro  which makes the app unable to connect to the yugen servers. If you go to yugen.to it redirects you to yugenanime.ro

Would probably be a easy fix, just change the first part of the URL in app/src/main/java/com/talent/animescrap/animesources/YugenSource.kt

**Comment by fakeyatogod** [comment]
552c4dc
