### ISSUE TITLE
Need good layout for player 🥲

### ISSUE THREAD

**Issue by fakeyatogod** [fakeyatogod/AnimeScrap#5]

**Comment by ShivamKun** [comment]
smoller buttons tho...

**Comment by fakeyatogod** [comment]
> smoller buttons tho...

You mean, making buttons smaller

**Comment by ShivamKun** [comment]
yeah...

**Comment by fakeyatogod** [comment]
> yeah...

Will try, why not

**Comment by fakeyatogod** [comment]
Designing the player layout is not really my cup of tea it seems.

**Comment by ShivamKun** [comment]
umm i donno much bout app development... but best of luck

**Comment by fakeyatogod** [comment]
Icons now smaller

**Comment by iCeY3** [comment]
![Screenshot_20220806-040452_AquaStream Beta](https://user-images.githubusercontent.com/98146929/183227579-2bb4fc30-6caa-4e84-b9c9-b03c553337c0.jpg)

**Comment by fakeyatogod** [comment]
Made timebar look better. Adjust some paddings.
