### ISSUE TITLE
Couple of suggestions 

### ISSUE THREAD

**Issue by iCeY3** [fakeyatogod/AnimeScrap#6]
MAL implementation
Sources: 9anime, allanime, zoro... Etc
Auto play next episode

**Comment by fakeyatogod** [comment]
Mal implementation. Nope. I don't want any logins or anything. Just simple app that's ready to go.

For more sources: Will try sometime.
Playing next episode on my list.

**Comment by MrConqueror** [comment]
> Mal implementation. Nope. I don't want any logins or anything. Just simple app that's ready to go.
> 
> For more sources: Will try sometime. Playing next episode on my list.

how about changing litle bit home UI

**Comment by fakeyatogod** [comment]
> > Mal implementation. Nope. I don't want any logins or anything. Just simple app that's ready to go.
> > For more sources: Will try sometime. Playing next episode on my list.
> 
> how about changing litle bit home UI

Designing is hard bro TT

**Comment by fakeyatogod** [comment]
> MAL implementation Sources: 9anime, allanime, zoro... Etc Auto play next episode

allanime and zoro added, 

keeping open until I add play next button.

**Comment by fakeyatogod** [comment]
Done in 2.1.0
